trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARTIFACT_NAME: 'Vulkan-Loader-Test-$(Build.BuildId)'

steps:
- script: |
    sudo apt update
    sudo apt install --yes software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt update
    sudo apt install --yes python3.7 python3.7-venv python3.7-dev
    sudo apt install --yes clang
    sudo python3.7 -m ensurepip
    sudo python3.7 -m pip install --upgrade pip
    sudo apt install --yes --no-install-recommends libwayland-dev libxrandr-dev
    sudo sysctl vm.mmap_rnd_bits=28
  displayName: 'Install dependencies'

#- script: |
#    echo Installing CMake version 3.17.2
#    wget https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-Linux-x86_64.sh
#    chmod +x cmake-3.17.2-Linux-x86_64.sh
#    ./cmake-3.17.2-Linux-x86_64.sh --skip-license --prefix=/usr/local
#  displayName: 'Pre-build step'

- script: |
    cmake -S. -B build -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTS=ON -D UPDATE_DEPS=ON -D LOADER_ENABLE_ADDRESS_SANITIZER=ON -D BUILD_WERROR=ON -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_C_COMPILER=clang
    cmake --build build
    ctest --output-on-failure --test-dir build/
    cmake --install build --prefix /tmp
  displayName: 'Build and Test'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: $(ARTIFACT_NAME)
    publishLocation: 'container'

